### ISSUE TITLE
cannot find package "launchpad.net/~niemeyer/goyaml/beta"

### ISSUE THREAD

**Issue by nfuhs** [olebedev/go-react-example#1]
I' m new to golang.. what I'm doing wrong?

This is my terminal output:

noby@Prometheus:~/env_go/src/github.com/olebedev/go-react-example$ make
find: "static": Datei oder Verzeichnis nicht gefunden
./node_modules/.bin/browserify -e bundle.js > static/bundle.js
/home/noby/env_go/bin/go-bindata -pkg=main -prefix=static -o=bindata.go static/...
noby@Prometheus:~/env_go/src/github.com/olebedev/go-react-example$ go run *.go
../config/config.go:16:2: cannot find package "launchpad.net/~niemeyer/goyaml/beta" in any of:
	/usr/local/go/src/launchpad.net/~niemeyer/goyaml/beta (from $GOROOT)
	/home/noby/env_go/src/launchpad.net/~niemeyer/goyaml/beta (from $GOPATH)
noby@Prometheus:~/env_go/src/github.com/olebedev/go-react-example$

**Comment by olebedev** [comment]
It looks like you have no one of dependencies for `config` package.
Please, ensure that you install it correctly. Basically, you may do this:
```
$ rm -rf src
$ go get ./... 
```

and try it again.
If the problem still exists, please let me know.

**Comment by nfuhs** [comment]
You were right I hadn't installed bazaar and so go get didnt work properly but I think its working now, this the code from test page:

<!doctype html>
<html data-reactid=".29wyyeywwz6" data-react-checksum="1579697310"><head data-reactid=".29wyyeywwz6.0"><link rel="stylesheet" href="/static/css/style.css" data-reactid=".29wyyeywwz6.0.0"><script src="/static/bundle.js" data-reactid=".29wyyeywwz6.0.1"></script><title data-reactid=".29wyyeywwz6.0.2">Go React Example</title></head><body class="App" data-reactid=".29wyyeywwz6.1"><div class="UserPage" data-reactid=".29wyyeywwz6.1.0"><h1 data-reactid=".29wyyeywwz6.1.0.0"><span data-reactid=".29wyyeywwz6.1.0.0.0">Hello, </span><span data-reactid=".29wyyeywwz6.1.0.0.1">Doe</span><span data-reactid=".29wyyeywwz6.1.0.0.2">!</span></h1><p data-reactid=".29wyyeywwz6.1.0.1"><span data-reactid=".29wyyeywwz6.1.0.1.0">Go to </span><a href="/users/ivan" data-reactid=".29wyyeywwz6.1.0.1.1"><span data-reactid=".29wyyeywwz6.1.0.1.1.0">/users/</span><span data-reactid=".29wyyeywwz6.1.0.1.1.1">ivan</span></a></p><p data-reactid=".29wyyeywwz6.1.0.2"><a href="/" data-reactid=".29wyyeywwz6.1.0.2.0">Logout</a></p></div></body></html>

Would you mind if I would later ask you some technical questions about this impressive stuff?

**Comment by olebedev** [comment]
Sure. I would gladly answer your questions.

On Thursday, March 19, 2015, Norbert Fuhs <notifications@github.com> wrote:

> You were right I hadn't installed bazaar and so go get didnt work properly
> but I think its working now, this the code from test page:
>
> <!doctype html>
> Go React Example
> Hello, Doe!
>
> Go to /users/ivan
>
> Logout <http:///>
>
> Would you mind if I would later ask you some technical questions about
> this impressive stuff?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olebedev/go-react-example/issues/1#issuecomment-83189764>
> .
>


-- 
---
Oleg
