### ISSUE TITLE
go run *.go fails with 'too many arguments in call to panicIf'

### ISSUE THREAD

**Issue by charl** [olebedev/go-react-example#10]
I followed the installation [instructions](https://github.com/olebedev/go-react-example).

When I run the example I get:

```
$ go run *.go
# command-line-arguments
./react.go:55: too many arguments in call to panicIf
```

```
$ go version
go version go1.4.2 darwin/amd64
```

**Comment by olebedev** [comment]
@charl Thanks for report!
I have just fixed this error. Please take a look https://github.com/olebedev/go-react-example/commit/b19e530c31948255d3685ae15afa3b5186b8f852.

BTW, I am recommended to use [this](https://github.com/olebedev/go-starter-kit) project instead.
