### ISSUE TITLE
error while getting code

### ISSUE THREAD

**Issue by barum** [olebedev/go-react-example#2]
I am getting the following:

 go get github.com/olebedev/go-react-example
# github.com/olebedev/go-react-example
projects/gocode/src/github.com/olebedev/go-react-example/app.go:56: undefined: Asset
projects/gocode/src/github.com/olebedev/go-react-example/react.go:50: undefined: Asset

**Comment by olebedev** [comment]
Sure. The project is not go-gettable. Please, use git clone instead.
