### ISSUE TITLE
error while using `window` object

### ISSUE THREAD

**Issue by lilee** [olebedev/go-react-example#3]
panic: ReferenceError: identifier 'window' undefined

**Comment by olebedev** [comment]
May I ask you provide full case? What exactly you try to do with window object.

**Comment by lilee** [comment]
I used with [Masonry](https://github.com/Masonry/Masonry) library

**Comment by olebedev** [comment]
I see. Masonry uses `absolute: position` for managed elements. So, there is no reason to use it as server side.  Basically, you haven't to use clientside library at server side. You may try call Masonry as `componentDidMount` react method.

**Comment by lilee** [comment]
Thanks, I fixed it
