### ISSUE TITLE
compile error when js is uglified

### ISSUE THREAD

**Issue by lilee** [olebedev/go-react-example#5]
panic: RangeError: compiler recursion limit (line 1)

https://github.com/svaarala/duktape/issues/67

**Comment by olebedev** [comment]
Yep, this is known problem with duktape. 
I use this Makefile rule to get it done:
```
%.min.js: %.js
	cat $< | uglifyjs -m 2>/dev/null > $@
```

**Comment by lilee** [comment]
but use gulp-uglify with option ```mangle``` will raise the same panic
