### ISSUE TITLE
undefined: Asset

### ISSUE THREAD

**Issue by Marini83** [olebedev/go-react-example#9]
Hello,

I am trying to get started with golang and I want to utilize your wonderful example using react as well.  After I run  'go get .\...'     the following errors show up:

github.com/go-react-example
./app.go:56: undefined: Asset
./react.go:50: undefined: Asset
./react.go:55: too many arguments in call to panicIf

**Comment by olebedev** [comment]
@Marini83 thanks for your interest!  Please take a look this https://github.com/olebedev/go-react-example/issues/2 issue.

----
BTW, I am working now with new [project](https://github.com/olebedev/go-starter-kit) , that is fully idiomatic react/flux app with [fetch polyfill](https://github.com/olebedev/go-duktape-fetch) for duktape and server side render. Maybe it would be more relevant for you.
